import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return 
  <div>
    <Head>
      <title>GigHub</title>
      <meta name='description' content='generated by next js' />
      <link rel="icon" href="/favicon.icon"/>
    </Head>
    
  </div>

  
}
